# Ejecutar las pruebas de Ghost realizadas con KRAKEN 

1. Descargar esta carpeta -> https://github.com/j-albarracin-uniandes/pruebas-automatizadas/tree/master/pruebas-kraken
2. Crear un usuario en GHOST y actualizar este archivo con el usuario y contraseña en este archivo https://github.com/j-albarracin-uniandes/pruebas-automatizadas/blob/master/pruebas-kraken/properties.json en los campos USERNAME y PASSWORD o utilizar las credenciales de uno que ya tengan y colocarlo ahi 
3. Ubicarse en la carpeta del proyecto y ejecutar este comando 
./node_modules/kraken-node/bin/kraken-node run
